export const USER_TYPE = {
  DEFAULT: 0,
  MICROSOFT: 1,
  FACEBOOK: 2,
  AMAZON: 3,
};

export const PROMOTION_TYPE = {
  PERCENTAGE_DISCOUNT: 'PERCENTAGE_DISCOUNT',
  MONEY_DISCOUNT: 'MONEY_DISCOUNT',
  GET_FREE_ITEM: 'GET_FREE_ITEM'
};
